=pod

=head1 Lorem ipsum dolor sit amet

Lorem ipsum E<quot>dolorE<quot> sit amet, E<lt>consectetuerE<gt> adipiscing elit. Nunc
volutpat faucibus loremE<mdash>In pellentesque tortor ac leo. Aenean sit
amet justo sed orci egestas sodales. Aenean risus sapien, pulvinar ut,
ultrices dictum, varius sit amet, tellus. 

=cut